# Generated by Django 4.0.6 on 2024-12-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_by_city', to='profession.profession')),
            ],
            options={
                'ordering': ['-share'],
            },
        ),
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_by_city', to='profession.profession')),
            ],
            options={
                'ordering': ['-avg_salary'],
            },
        ),
    ]
