# Generated by Django 4.0.6 on 2024-12-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0002_vacanciesbycity_salarybycity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.CharField(help_text='Unique ID for the vacancy from the API', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('region', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
            ],
        ),
    ]
